// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerControllerConfig) DeepCopyInto(out *CertManagerControllerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Flags.DeepCopyInto(&out.Flags)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerControllerConfig.
func (in *CertManagerControllerConfig) DeepCopy() *CertManagerControllerConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerControllerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerControllerFlags) DeepCopyInto(out *CertManagerControllerFlags) {
	*out = *in
	if in.AutoCertificateAnnotations != nil {
		in, out := &in.AutoCertificateAnnotations, &out.AutoCertificateAnnotations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Controllers != nil {
		in, out := &in.Controllers, &out.Controllers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNS01RecursiveNameservers != nil {
		in, out := &in.DNS01RecursiveNameservers, &out.DNS01RecursiveNameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.LogBacktraceAt = in.LogBacktraceAt
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerControllerFlags.
func (in *CertManagerControllerFlags) DeepCopy() *CertManagerControllerFlags {
	if in == nil {
		return nil
	}
	out := new(CertManagerControllerFlags)
	in.DeepCopyInto(out)
	return out
}
