# permissions for end users to edit certmanagerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certmanagerdeployment-editor-role
rules:
- apiGroups:
  - operators.opdev.io
  resources:
  - certmanagerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.opdev.io
  resources:
  - certmanagerdeployments/status
  verbs:
  - get
