// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/apps/v1"
	v1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeployment) DeepCopyInto(out *CertManagerDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeployment.
func (in *CertManagerDeployment) DeepCopy() *CertManagerDeployment {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeploymentCondition) DeepCopyInto(out *CertManagerDeploymentCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeploymentCondition.
func (in *CertManagerDeploymentCondition) DeepCopy() *CertManagerDeploymentCondition {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeploymentCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeploymentList) DeepCopyInto(out *CertManagerDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManagerDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeploymentList.
func (in *CertManagerDeploymentList) DeepCopy() *CertManagerDeploymentList {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeploymentSpec) DeepCopyInto(out *CertManagerDeploymentSpec) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	in.DangerZone.DeepCopyInto(&out.DangerZone)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeploymentSpec.
func (in *CertManagerDeploymentSpec) DeepCopy() *CertManagerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeploymentStatus) DeepCopyInto(out *CertManagerDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CertManagerDeploymentCondition, len(*in))
		copy(*out, *in)
	}
	if in.DeploymentConditions != nil {
		in, out := &in.DeploymentConditions, &out.DeploymentConditions
		*out = make([]ManagedDeploymentWithConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CRDConditions != nil {
		in, out := &in.CRDConditions, &out.CRDConditions
		*out = make([]ManagedCRDWithConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeploymentStatus.
func (in *CertManagerDeploymentStatus) DeepCopy() *CertManagerDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DangerZone) DeepCopyInto(out *DangerZone) {
	*out = *in
	if in.ImageOverrides != nil {
		in, out := &in.ImageOverrides, &out.ImageOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ContainerArgOverrides != nil {
		in, out := &in.ContainerArgOverrides, &out.ContainerArgOverrides
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DangerZone.
func (in *DangerZone) DeepCopy() *DangerZone {
	if in == nil {
		return nil
	}
	out := new(DangerZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCRDWithConditions) DeepCopyInto(out *ManagedCRDWithConditions) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1beta1.CustomResourceDefinitionCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCRDWithConditions.
func (in *ManagedCRDWithConditions) DeepCopy() *ManagedCRDWithConditions {
	if in == nil {
		return nil
	}
	out := new(ManagedCRDWithConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDeploymentWithConditions) DeepCopyInto(out *ManagedDeploymentWithConditions) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.DeploymentCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDeploymentWithConditions.
func (in *ManagedDeploymentWithConditions) DeepCopy() *ManagedDeploymentWithConditions {
	if in == nil {
		return nil
	}
	out := new(ManagedDeploymentWithConditions)
	in.DeepCopyInto(out)
	return out
}
