// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeployment) DeepCopyInto(out *CertManagerDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeployment.
func (in *CertManagerDeployment) DeepCopy() *CertManagerDeployment {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeploymentList) DeepCopyInto(out *CertManagerDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertManagerDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeploymentList.
func (in *CertManagerDeploymentList) DeepCopy() *CertManagerDeploymentList {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertManagerDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeploymentSpec) DeepCopyInto(out *CertManagerDeploymentSpec) {
	*out = *in
	in.DangerZone.DeepCopyInto(&out.DangerZone)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeploymentSpec.
func (in *CertManagerDeploymentSpec) DeepCopy() *CertManagerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerDeploymentStatus) DeepCopyInto(out *CertManagerDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerDeploymentStatus.
func (in *CertManagerDeploymentStatus) DeepCopy() *CertManagerDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(CertManagerDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DangerZone) DeepCopyInto(out *DangerZone) {
	*out = *in
	if in.ImageOverrides != nil {
		in, out := &in.ImageOverrides, &out.ImageOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DangerZone.
func (in *DangerZone) DeepCopy() *DangerZone {
	if in == nil {
		return nil
	}
	out := new(DangerZone)
	in.DeepCopyInto(out)
	return out
}
